<a href="https://colab.research.google.com/github/fayzi-dev/machin_learning/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Example Numpy Code by Mohammad fayzi

# Install Numpy:Install it using this command:

> #pip


>pip3





In [14]:
pip install numpy
pip3 install numpy

# **Import Numpy : show version numpy**
### *NumPy is usually imported under the np alias.*

In [ ]:
import numpy as np
np.__version__

'1.26.4'

**Create a new arrray by Numpy**

In [ ]:
arr = np.array([1, 2, 3, 4])
# print(arr)
arr.shape

(4,)

**Use a tuple to create a NumPy array:**



In [ ]:
arr_tuple = np.array((1 ,2 ,3 , 4, 5, 6))
arr_tuple

array([1, 2, 3, 4, 5, 6])

# ایجاد آرایه دو بعدی

In [16]:
arr_2_D = np.array([[10,  20, 30],[200, 300, 400]])
print(arr_2_D)

[[ 10  20  30]
 [200 300 400]]


#  (shape) برای نمایش تعداد بعد آرایه

In [17]:
arr_2_D.shape

(2, 3)