# Import Package

In [375]:
import numpy as np
import pandas as pd

import matplotlib.pyplot as plt
import plotly.express as px

In [376]:
df = pd.read_csv('Datasets/survey_results_public.csv')

In [377]:
df.shape

(73268, 79)

In [378]:
df.columns

Index(['ResponseId', 'MainBranch', 'Employment', 'RemoteWork',
       'CodingActivities', 'EdLevel', 'LearnCode', 'LearnCodeOnline',
       'LearnCodeCoursesCert', 'YearsCode', 'YearsCodePro', 'DevType',
       'OrgSize', 'PurchaseInfluence', 'BuyNewTool', 'Country', 'Currency',
       'CompTotal', 'CompFreq', 'LanguageHaveWorkedWith',
       'LanguageWantToWorkWith', 'DatabaseHaveWorkedWith',
       'DatabaseWantToWorkWith', 'PlatformHaveWorkedWith',
       'PlatformWantToWorkWith', 'WebframeHaveWorkedWith',
       'WebframeWantToWorkWith', 'MiscTechHaveWorkedWith',
       'MiscTechWantToWorkWith', 'ToolsTechHaveWorkedWith',
       'ToolsTechWantToWorkWith', 'NEWCollabToolsHaveWorkedWith',
       'NEWCollabToolsWantToWorkWith', 'OpSysProfessional use',
       'OpSysPersonal use', 'VersionControlSystem', 'VCInteraction',
       'VCHostingPersonal use', 'VCHostingProfessional use',
       'OfficeStackAsyncHaveWorkedWith', 'OfficeStackAsyncWantToWorkWith',
       'OfficeStackSyncHaveWork

In [379]:
df.head()

ResponseId                                         MainBranch  \
0           1                                      None of these   
1           2                     I am a developer by profession   
2           3  I am not primarily a developer, but I write co...   
3           4                     I am a developer by profession   
4           5                     I am a developer by profession   

            Employment                            RemoteWork  \
0                  NaN                                   NaN   
1  Employed, full-time                          Fully remote   
2  Employed, full-time  Hybrid (some remote, some in-person)   
3  Employed, full-time                          Fully remote   
4  Employed, full-time  Hybrid (some remote, some in-person)   

                           CodingActivities  \
0                                       NaN   
1  Hobby;Contribute to open-source projects   
2                                     Hobby   
3              I don’t code outside of work   
4                                     Hobby   

                                           EdLevel  \
0                                              NaN   
1                                              NaN   
2  Master’s degree (M.A., M.S., M.Eng., MBA, etc.)   
3     Bachelor’s degree (B.A., B.S., B.Eng., etc.)   
4     Bachelor’s degree (B.A., B.S., B.Eng., etc.)   

                                           LearnCode  \
0                                                NaN   
1                                                NaN   
2  Books / Physical media;Friend or family member...   
3  Books / Physical media;School (i.e., Universit...   
4  Other online resources (e.g., videos, blogs, f...   

                                     LearnCodeOnline LearnCodeCoursesCert  \
0                                                NaN                  NaN   
1                                                NaN                  NaN   
2  Technical documentation;Blogs;Programming Game...                  NaN   
3                                                NaN                  NaN   
4  Technical documentation;Blogs;Stack Overflow;O...                  NaN   

  YearsCode  ... TimeSearching TimeAnswering Onboarding ProfessionalTech  \
0       NaN  ...           NaN           NaN        NaN              NaN   
1       NaN  ...           NaN           NaN        NaN              NaN   
2        14  ...           NaN           NaN        NaN              NaN   
3        20  ...           NaN           NaN        NaN              NaN   
4         8  ...           NaN           NaN        NaN              NaN   

  TrueFalse_1 TrueFalse_2 TrueFalse_3           SurveyLength  \
0         NaN         NaN         NaN                    NaN   
1         NaN         NaN         NaN               Too long   
2         NaN         NaN         NaN  Appropriate in length   
3         NaN         NaN         NaN  Appropriate in length   
4         NaN         NaN         NaN               Too long   

                   SurveyEase ConvertedCompYearly  
0                         NaN                 NaN  
1                   Difficult                 NaN  
2  Neither easy nor difficult             40205.0  
3                        Easy            215232.0  
4                        Easy                 NaN  

[5 rows x 79 columns]

In [380]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 73268 entries, 0 to 73267
Data columns (total 79 columns):
 #   Column                          Non-Null Count  Dtype  
---  ------                          --------------  -----  
 0   ResponseId                      73268 non-null  int64  
 1   MainBranch                      73268 non-null  object 
 2   Employment                      71709 non-null  object 
 3   RemoteWork                      58958 non-null  object 
 4   CodingActivities                58899 non-null  object 
 5   EdLevel                         71571 non-null  object 
 6   LearnCode                       71580 non-null  object 
 7   LearnCodeOnline                 50685 non-null  object 
 8   LearnCodeCoursesCert            29389 non-null  object 
 9   YearsCode                       71331 non-null  object 
 10  YearsCodePro                    51833 non-null  object 
 11  DevType                         61302 non-null  object 
 12  OrgSize                         

# Visualization

In [381]:
def plot_line_chart(df, column, line=''):
    if line == '':
        line = df[column].value_counts().keys()[0:20]
    data = df[column].value_counts()[0:20]
    fig = px.line(x=line, y=data)
    fig.show()
def plot_bar_chart(df, column, line=''):
    if line == '':
        line = df[column].value_counts().keys()[0:20]
    data = df[column].value_counts()[0:20]
    fig = px.bar(x=line, y=data)
    fig.show()

def plot_pie_chart(df, column, line=''):
    if line == '':
        line = df[column].value_counts().keys()[0:20]
    data = df[column].value_counts()[0:20]
    fig = px.pie(names=line, values=data)
    fig.show()    

In [382]:
plot_bar_chart(df, 'Country')
plot_line_chart(df, 'Country')


In [383]:
line = ['developer', 'student', 'half-developer', 'hobby', 'used-developer', 'neither']
plot_line_chart(df, 'MainBranch', line)
plot_bar_chart(df, 'MainBranch', line)
plot_pie_chart(df, 'MainBranch', line)

In [384]:
plot_bar_chart(df,'Employment')
plot_line_chart(df,'Employment')
plot_pie_chart(df,'Employment')

In [385]:
plot_bar_chart(df,'EdLevel')
# plot_line_chart(df,'EdLevel')
plot_pie_chart(df,'EdLevel')

In [386]:
plot_bar_chart(df,'YearsCodePro')
plot_pie_chart(df,'YearsCodePro')

In [387]:
df[['DevType']]

DevType
0                                                    NaN
1                                                    NaN
2      Data scientist or machine learning specialist;...
3                                  Developer, full-stack
4      Developer, front-end;Developer, full-stack;Dev...
...                                                  ...
73263                                Developer, back-end
73264      Data scientist or machine learning specialist
73265  Developer, full-stack;Developer, desktop or en...
73266  Developer, front-end;Developer, desktop or ent...
73267  Developer, front-end;Engineer, data;Engineer, ...

[73268 rows x 1 columns]

In [388]:
df_DevType = pd.DataFrame()
num = 0
str_list = []

for i in df['DevType']:
    num = num + 1
    if pd.isnull(i):
        continue
    data = i.split(';')
    for j in data:
        str_list.append(j)
df_DevType = pd.DataFrame(str_list, columns=['DevType'])
df_DevType.value_counts()

DevType                                      
Developer, full-stack                            28701
Developer, back-end                              26595
Developer, front-end                             15915
Developer, desktop or enterprise applications     9546
Developer, mobile                                 7634
DevOps specialist                                 6170
Student                                           5595
Cloud infrastructure engineer                     5283
Database administrator                            4934
System administrator                              4908
Developer, embedded applications or devices       3923
Project manager                                   3897
Designer                                          3764
Engineer, data                                    3600
Engineering manager                               3574
Data scientist or machine learning specialist     3424
Data or business analyst                          3201
Developer, QA or te

In [389]:
plot_bar_chart(df_DevType, 'DevType')
plot_pie_chart(df_DevType, 'DevType')

#Feature Engineering

In [390]:
df.sample()

ResponseId                   MainBranch  \
2470        2471  I code primarily as a hobby   

                                             Employment RemoteWork  \
2470  Student, full-time;Not employed, but looking f...        NaN   

     CodingActivities                                            EdLevel  \
2470              NaN  Secondary school (e.g. American high school, G...   

                                              LearnCode  \
2470  Books / Physical media;Friend or family member...   

                                        LearnCodeOnline LearnCodeCoursesCert  \
2470  Technical documentation;Blogs;Stack Overflow;O...                  NaN   

     YearsCode  ... TimeSearching TimeAnswering Onboarding ProfessionalTech  \
2470         5  ...           NaN           NaN        NaN              NaN   

     TrueFalse_1 TrueFalse_2 TrueFalse_3           SurveyLength SurveyEase  \
2470         NaN         NaN         NaN  Appropriate in length       Easy   

     ConvertedCompYearly  
2470                 NaN  

[1 rows x 79 columns]

In [391]:
df = df[['Country', 'EdLevel', 'YearsCodePro', 'ConvertedCompYearly']]
df = df.rename({'ConvertedCompYearly':'Salary'}, axis='columns')
df.head()

Country  \
0                                                NaN   
1                                             Canada   
2  United Kingdom of Great Britain and Northern I...   
3                                             Israel   
4                           United States of America   

                                           EdLevel YearsCodePro    Salary  
0                                              NaN          NaN       NaN  
1                                              NaN          NaN       NaN  
2  Master’s degree (M.A., M.S., M.Eng., MBA, etc.)            5   40205.0  
3     Bachelor’s degree (B.A., B.S., B.Eng., etc.)           17  215232.0  
4     Bachelor’s degree (B.A., B.S., B.Eng., etc.)            3       NaN

In [392]:
df = df[df['Salary'].notnull()]
df.head()

Country  \
2   United Kingdom of Great Britain and Northern I...   
3                                              Israel   
8                                         Netherlands   
10  United Kingdom of Great Britain and Northern I...   
11                           United States of America   

                                            EdLevel YearsCodePro    Salary  
2   Master’s degree (M.A., M.S., M.Eng., MBA, etc.)            5   40205.0  
3      Bachelor’s degree (B.A., B.S., B.Eng., etc.)           17  215232.0  
8   Master’s degree (M.A., M.S., M.Eng., MBA, etc.)            6   49056.0  
10     Bachelor’s degree (B.A., B.S., B.Eng., etc.)            2   60307.0  
11     Bachelor’s degree (B.A., B.S., B.Eng., etc.)           10  194400.0

In [393]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 38071 entries, 2 to 73121
Data columns (total 4 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   Country       38071 non-null  object 
 1   EdLevel       38054 non-null  object 
 2   YearsCodePro  37935 non-null  object 
 3   Salary        38071 non-null  float64
dtypes: float64(1), object(3)
memory usage: 1.5+ MB


In [394]:
df.dropna()
df.isnull().sum()

Country           0
EdLevel          17
YearsCodePro    136
Salary            0
dtype: int64

In [395]:
df.columns

Index(['Country', 'EdLevel', 'YearsCodePro', 'Salary'], dtype='object')

In [396]:
df['Country'].value_counts()

Country
United States of America                                8707
Germany                                                 2912
United Kingdom of Great Britain and Northern Ireland    2657
India                                                   2173
Canada                                                  1481
                                                        ... 
Fiji                                                       1
Palau                                                      1
Monaco                                                     1
Saint Lucia                                                1
Seychelles                                                 1
Name: count, Length: 159, dtype: int64

In [397]:
def print_unique_col_values(df):
    for column in df:
        if df[column].dtypes == 'object':
            print(f'{column}: {df[column].unique()}')

In [398]:
print_unique_col_values(df)

Country: ['United Kingdom of Great Britain and Northern Ireland' 'Israel'
 'Netherlands' 'United States of America' 'Czech Republic' 'Austria'
 'Italy' 'Canada' 'Germany' 'Ireland' 'Poland' 'Madagascar' 'Norway'
 'Taiwan' 'France' 'Brazil' 'Uruguay' 'Sweden' 'Spain' 'Turkey' 'Romania'
 'Singapore' 'India' 'Belgium' 'Bulgaria' 'Greece' 'Portugal'
 'Russian Federation' 'Saudi Arabia' 'Mexico' 'Kenya' 'Switzerland'
 'Latvia' 'South Africa' 'Thailand' 'China' 'Montenegro' 'Finland'
 'Slovakia' 'Japan' 'Denmark' 'Australia' 'Viet Nam' 'Argentina' 'Hungary'
 'Tunisia' 'Bangladesh' 'Ukraine' 'Maldives' 'Hong Kong (S.A.R.)' 'Egypt'
 'Serbia' 'Pakistan' 'Nepal' 'Croatia' 'Indonesia'
 'Bosnia and Herzegovina' 'Armenia' 'Lithuania'
 'Iran, Islamic Republic of...' 'Belarus' 'Costa Rica' 'Mauritius'
 'Estonia' 'Kazakhstan' 'Morocco' 'Philippines' 'Chile' 'New Zealand'
 'Slovenia' 'Ecuador' 'Cyprus' 'Peru' 'Colombia' 'Afghanistan' 'Nicaragua'
 'Andorra' 'Republic of Korea' 'Lebanon' 'South Korea' 'M

In [399]:
# def shorten_categories(categories, cutoff):
#     categorical_map = {}
#     for i in range(len(categories)):
#         if categories.values[i] >= cutoff:
#             categorical_map[categories.index[i]] = categories.index[i]
#         else:
#             categorical_map[categories.index[i]] = 'Other'
#     return categorical_map
def shorten_categories(categories, cutoff):
    return {
        category: category if value >= cutoff else "Other"
        for category, value in zip(categories.index, categories.values)
    }


In [400]:
country_map = shorten_categories(df.Country.value_counts(), 199)
df['Country'] = df['Country'].map(country_map)
df.Country.value_counts()

Country
United States of America                                8707
Other                                                   4381
Germany                                                 2912
United Kingdom of Great Britain and Northern Ireland    2657
India                                                   2173
Canada                                                  1481
France                                                  1378
Brazil                                                  1283
Spain                                                    996
Poland                                                   977
Netherlands                                              900
Australia                                                833
Italy                                                    812
Sweden                                                   665
Russian Federation                                       534
Switzerland                                              520
Turkey          

In [401]:
fig  = px.box(df, x='Country', y='Salary')  #show Outlier
fig.show()

In [402]:
# df = df[df['Salary'] <= 200000]
# df = df[df['Salary'] >= 10000]
# df = df[df['Country'] != 'Other']
df = df[(df['Salary'] <= 200000) & (df['Salary'] >= 10000) & (df['Country'] != 'Other')]

In [403]:
fig  = px.box(df, x='Country', y='Salary')  #show Outlier
fig.show()

In [404]:
df['YearsCodePro'].unique()

array(['5', '6', '2', '10', '4', '22', '20', '9', '14', '21', '15', '3',
       '25', '7', '8', '12', '19', '1', '17', '24', '11', '23',
       'Less than 1 year', '18', '40', '37', '46', '13', '32', '31', '39',
       '27', '28', '16', '30', '34', '35', '26', '42', '38', '36', '43',
       '41', '44', '29', nan, '33', '45', '48', '50', '47',
       'More than 50 years', '49'], dtype=object)

In [405]:
def clean_experience(x):
    if x == 'More than 50 years':
        return 50
    if x == 'Less than 1 year':
        return 0.5
    return float(x)

df['YearsCodePro'] = df['YearsCodePro'].apply(clean_experience)

In [406]:
df['YearsCodePro'].unique()

array([ 5. ,  6. ,  2. , 10. ,  4. , 22. , 20. ,  9. , 14. , 21. , 15. ,
        3. , 25. ,  7. ,  8. , 12. , 19. ,  1. , 17. , 24. , 11. , 23. ,
        0.5, 18. , 40. , 37. , 46. , 13. , 32. , 31. , 39. , 27. , 28. ,
       16. , 30. , 34. , 35. , 26. , 42. , 38. , 36. , 43. , 41. , 44. ,
       29. ,  nan, 33. , 45. , 48. , 50. , 47. , 49. ])

In [407]:
df['EdLevel'].unique()

array(['Master’s degree (M.A., M.S., M.Eng., MBA, etc.)',
       'Bachelor’s degree (B.A., B.S., B.Eng., etc.)',
       'Secondary school (e.g. American high school, German Realschule or Gymnasium, etc.)',
       'Something else', 'Associate degree (A.A., A.S., etc.)',
       'Some college/university study without earning a degree',
       'Professional degree (JD, MD, etc.)',
       'Other doctoral degree (Ph.D., Ed.D., etc.)',
       'Primary/elementary school', nan], dtype=object)

In [408]:
# def clean_education(x):
#     if 'Bachelor’s degree' in x:
#         return 'Bachelor’s degree'
#     if 'Master’s degree' in x:
#         return 'Master’s degree'
#     if 'Professional degree' in x or 'Other doctoral' in x:
#         return 'Post grad'
#     return 'Less than a bachelor'
# 

# 2.
# def clean_education(x):
#     if 'Bachelor’s degree' in x:
#         return 'Bachelor’s degree'
#     elif 'Master’s degree' in x:
#         return 'Master’s degree'
#     elif 'Professional degree' in x or 'Other doctoral' in x:
#         return 'Post grad'
#     else:
#         return 'Less than a bachelor'


# 3.   show error TypeError: argument of type 'float' is not iterable
def clean_education(x):
    if isinstance(x, str):
        if 'Bachelor’s degree' in x:
            return 'Bachelor’s degree'
        if 'Master’s degree' in x:
            return 'Master’s degree'
        if 'Professional degree' in x or 'Other doctoral' in x:
            return 'Post grad'
    return 'Less than a bachelor'


In [409]:
# Apply the function
df['EdLevel'] = df['EdLevel'].apply(clean_education)

# Check the unique values to ensure proper categorization
print(df['EdLevel'].unique())
# print(df['EdLevel'].value_counts())


['Master’s degree' 'Bachelor’s degree' 'Less than a bachelor' 'Post grad']


In [410]:
df.sample(5)

Country               EdLevel  YearsCodePro   Salary
9927    France  Less than a bachelor          11.0  44790.0
43981    India     Bachelor’s degree           0.5  12897.0
10496    India     Bachelor’s degree           5.0  74651.0
48454   France       Master’s degree           5.0  45430.0
44468  Germany     Bachelor’s degree           0.5  42657.0

# Model Training

In [411]:
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.impute import SimpleImputer
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression

In [412]:
X =df.drop('Salary', axis=1)
# X = df.iloc[:, :3]
y = df['Salary']


In [413]:
# Numeric pipeline with imputer and scaler
numeric_pipeline = Pipeline([
    ('imputer', SimpleImputer(strategy='mean')),
    ('scale', StandardScaler())
])
# Categorical pipeline
categorical_pipeline = Pipeline([('OneHot', OneHotEncoder(handle_unknown='ignore'))])

# Column transformer
transformer = ColumnTransformer(
    transformers=[
        ('num', numeric_pipeline, ['YearsCodePro']),
        ('cat', categorical_pipeline, ['Country', 'EdLevel'])
    ]
)

In [414]:
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.10, random_state=1234)

In [415]:
X_train 

Country               EdLevel  YearsCodePro
10576                    Norway       Master’s degree           5.0
21186                   Finland       Master’s degree           5.0
20640               Switzerland       Master’s degree          10.0
55983  United States of America  Less than a bachelor          45.0
1255                     Canada     Bachelor’s degree           9.0
...                         ...                   ...           ...
71865                    Brazil     Bachelor’s degree           9.0
59810  United States of America       Master’s degree          23.0
2750                     Canada     Bachelor’s degree          12.0
64303                     Spain       Master’s degree           1.0
70732               Netherlands     Bachelor’s degree           7.0

[25493 rows x 3 columns]

In [416]:
mlpipe_1 = Pipeline([('Transformer',transformer), ('lr', LinearRegression())])

In [417]:
mlpipe_1.fit(X_train, y_train)

Pipeline(steps=[('Transformer',
                 ColumnTransformer(transformers=[('num',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer()),
                                                                  ('scale',
                                                                   StandardScaler())]),
                                                  ['YearsCodePro']),
                                                 ('cat',
                                                  Pipeline(steps=[('OneHot',
                                                                   OneHotEncoder(handle_unknown='ignore'))]),
                                                  ['Country', 'EdLevel'])])),
                ('lr', LinearRegression())])

In [418]:
y_hat = mlpipe_1.predict(X_test)
y_hat

array([ 80319.92229125,  67102.65676703,  55594.82677535, ...,
       125647.08868431,  91627.32420681, 120430.15068015])

In [420]:
from sklearn.metrics import r2_score, mean_squared_error
error = np.sqrt(mean_squared_error(y_test, y_hat))
print('${:,.02f}'.format(error))

$31,999.09


# Training a new model using Decision Tree

In [422]:
from sklearn.tree import DecisionTreeRegressor

mlpipe_2 = Pipeline([('Transformer',transformer), ('dt', DecisionTreeRegressor())])

In [423]:
mlpipe_2.fit(X_train, y_train)

Pipeline(steps=[('Transformer',
                 ColumnTransformer(transformers=[('num',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer()),
                                                                  ('scale',
                                                                   StandardScaler())]),
                                                  ['YearsCodePro']),
                                                 ('cat',
                                                  Pipeline(steps=[('OneHot',
                                                                   OneHotEncoder(handle_unknown='ignore'))]),
                                                  ['Country', 'EdLevel'])])),
                ('dt', DecisionTreeRegressor())])

In [424]:
y_hat = mlpipe_2.predict(X_test)
y_hat

array([ 73323.53846154,  61210.62686567,  52593.34375   , ...,
       138098.08296943, 108484.62962963, 105746.25      ])

In [425]:
from sklearn.metrics import r2_score, mean_squared_error
error = np.sqrt(mean_squared_error(y_test, y_hat))
print('${:,.02f}'.format(error))

$33,339.22


# Training a new model using RandomForestRegressor

In [426]:
from sklearn.ensemble import RandomForestRegressor
mlpipe_3 = Pipeline([('Transformer', transformer), ('rf', RandomForestRegressor())])
mlpipe_3.fit(X_train, y_train)
y_hat = mlpipe_3.predict(X_test)
y_hat

array([ 72366.54277937,  61308.99787553,  52410.23654136, ...,
       138046.29094287, 107433.4972712 , 107991.95322222])

In [427]:
error = np.sqrt(mean_squared_error(y_test, y_hat))
print('${:,.02f}'.format(error))

$32,314.61


# Training a new model using XGBRegressor

In [428]:
from xgboost import XGBRegressor
mlpipe_4 = Pipeline([('Transformer', transformer), ('xgb', XGBRegressor())])
mlpipe_4.fit(X_train, y_train)
y_hat = mlpipe_4.predict(X_test)
y_hat

array([ 74540.305,  59602.48 ,  53173.027, ..., 138118.16 , 105686.21 ,
       113742.18 ], dtype=float32)

In [429]:
error = np.sqrt(mean_squared_error(y_test, y_hat))
print('${:,.02f}'.format(error))

$31,089.20


# Pridect a New Data

In [438]:
X_new = np.array([['Iran, Islamic Republic of...','Master’s degree', 5]])
X_new

array([['Iran, Islamic Republic of...', 'Master’s degree', '5']],
      dtype='<U28')

In [439]:
columns = ['Country', 'EdLevel', 'YearsCodePro']
X_new_df = pd.DataFrame(X_new, columns= columns)
X_new_df

Country          EdLevel YearsCodePro
0  Iran, Islamic Republic of...  Master’s degree            5

In [440]:
prediction = mlpipe_4.predict(X_new_df)
prediction

array([63018.22], dtype=float32)

# Export out model

In [441]:
import joblib

In [442]:
joblib.dump(mlpipe_4, 'mymodel.joblib')

['mymodel.joblib']

In [443]:
model = joblib.load('mymodel.joblib')

In [444]:
y_pred = model.predict(X_test)
y_pred

array([ 74540.305,  59602.48 ,  53173.027, ..., 138118.16 , 105686.21 ,
       113742.18 ], dtype=float32)